#!/usr/bin/python
# -*- coding:UTF-8 -*-

class Text(object): 

   TEXT1  =  "one weixin can't have more eos account"
   TEXT2  = "one eos account can't have more weixin"
   TEXT3 =  "init accounts failed"
   TEXT4 = "add account failed"
   TEXT5 = "add account success"
   TEXT6 = "del acccount"
   TEXT7 = "delacccount fail"
   TEXT8 = "AddAccount"
   TEXT9 = "initAccounts"
   TEXT10 = "getBlockInfo %d"
   TEXT11 = "getBlockInfo error"
   TEXT12 = "getAccount"
   TEXT13 = "getAccount error "
   TEXT14 = "sendMsg"
   TEXT15 = "sendMsg error"
   TEXT16 = "sendTransertMsg"
   TEXT17 = "sendTransertMsg error"
   TEXT18 = "sendVoteMsg"
   TEXT19 = "sendVoteMsg error"
   TEXT20 = "getInfo"
   TEXT21 = "getInfo error"
   TEXT22 = "没有相应的命令"
   TEXT23 = 'EOS账号不存在'
   TEXT24 = "EOS账户绑定成功!"
   TEXT25 = "0.0000 EOS"
   TEXT26 = "欢迎使用EOS监控系统！\n\r功能:\n\r  c1 xxx(绑定EOS账户xxx)\n\r  c2 xxx(查询账户xxx信息)\n\r  转账通知(需绑定EOS账号)\n\r  投票通知(需绑定EOS账号)\n\r  help(帮助命令)"
   TEXT27 = "parseBlock"
   TEXT28 = "parseTransaction"
   TEXT29 = "parseAction"
   TEXT30 = "intsert access_tbl error" 
   TEXT31 = "insert sucess"
   TEXT32 = "收到消息{0}"
   TEXT33 = "收到事件{0}"
   TEXT34 = "get account"
   TEXT35 = "subscribe"
   TEXT36 = "bindEosAccount"
   TEXT37 = "该微信注册EOS账户超过上限"
   TEXT38 = "该EOS账户注册超过上限"
   TEXT39 = "该微信已经注册该EOS账户"
   TEXT40 = "有人为您投票了"
   TEXT41 = "EOS超级节点投票"
   TEXT42 = "{0}为{1}进行了投票"
   TEXT43 = "您的账户最新交易信息"
   TEXT44 = "EOS转账"
   TEXT45 = "{0}向{1}进行了转帐"
   TEXT46 = "余额:  {0}\n\rRAM: {1}KB/{2}KB\n\r\n\rCPU:      \r\n  Used:       {3}us\n\r Available:{4}us\n\r Max:         {5}us\n\r\n\rNET:      \r\n  Used:       {6}KB\n\r Available:{7}KB\n\r Max:         {8}KB"

